name: Lint Docs
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Formatting
        # npx will automatically download and run the latest prettier
        run: npx prettier --write "**/*.mdx"
