name: Trigger Site Build

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: rippedpiracy/site
          event-type: docs_updated
